apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "azure_metrics_exporter.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "azure_metrics_exporter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "azure_metrics_exporter.chart" . }}
data:
  configuration.yaml: |-
    configuration: |-
{{ toYaml .Values.configuration | indent 6}}
  azure.toml: |-
    [template]
    src = "azure.yml.tmpl"
    dest = "/data/azure.yml"
    mode = "0644"
    keys = ["/configuration"]
  azure.yml.tmpl: |-
    credentials:
      subscription_id: {{ `{{ getenv "subscription_id" }}` }}
      client_id: {{ `{{ getenv "client_id" }}` }}
      client_secret: {{ `{{ getenv "client_secret" }}` }}
      tenant_id: {{ `{{ getenv "tenant_id" }}` }}
    {{ `{{ getv "/configuration" }}` }}
