apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "azure_metrics_exporter.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "azure_metrics_exporter.name" . }}
    helm.sh/chart: {{ include "azure_metrics_exporter.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- with .Values.labels }}
{{ toYaml . | indent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "azure_metrics_exporter.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "azure_metrics_exporter.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
{{- with .Values.labels }}
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
      volumes:
        - name: config-volume
          emptyDir: {}
        - name: confd-templates
          configMap:
            name: {{ include "azure_metrics_exporter.fullname" . }}
            items:
              - key: azure.yml.tmpl
                path: azure.yml.tmpl
        - name: confd-config
          configMap:
            name: {{ include "azure_metrics_exporter.fullname" . }}
            items:
              - key: azure.toml
                path: azure.toml
        - name: confd-sources
          configMap:
            name: {{ include "azure_metrics_exporter.fullname" . }}
            items:
              - key: configuration.yaml
                path: configuration.yaml
      initContainers:
        - name: confd
          image: fxinnovation/confd:0.1.0
          args:
            - '-onetime'
            - '-backend=file'
            - '-file=/data/configuration.yaml'
          volumeMounts:
            - name: config-volume
              mountPath: /data
            - name: confd-config
              mountPath: /etc/confd/conf.d
            - name: confd-sources
              mountPath: /etc/confd/sources
            - name: confd-templates
              mountPath: /etc/confd/templates
          env:
            - name: subscription_id
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret }}
                  key: subscription_id
            - name: client_id
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret }}
                  key: client_id
            - name: tenant_id
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret }}
                  key: tenant_id
            - name: client_secret
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret }}
                  key: client_secret
      containers:
        - name: azure-metrics-exporter
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - name: config-volume
            mountPath: /opt/azure_metrics_exporter/conf
          ports:
            - name: http
              containerPort: 9276
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
